/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas_Recepcion;

import Conexion.Conexion;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class pnlRegistroTurno extends javax.swing.JPanel {

        Conexion cx;
    /**
     * Creates new form pnlRegistroTurno
     */
    public pnlRegistroTurno() {
        initComponents();
        cx = new Conexion("rtv_ist17j");
        traerNroTurno();
        comboVehiculo();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        cbxGasesa = new javax.swing.JCheckBox();
        cbxLucesa = new javax.swing.JCheckBox();
        cbxFrenosa = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnRegistrarCliente = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnRegistrarCliente1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        comboVehiculo = new javax.swing.JComboBox<>();
        lblCodigo = new javax.swing.JTextField();
        lblTotala = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(880, 530));

        jPanel1.setPreferredSize(new java.awt.Dimension(880, 530));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setEnabled(false);
        jPanel16.setPreferredSize(new java.awt.Dimension(880, 530));

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));

        cbxGasesa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxGasesa.setText("Gases");
        cbxGasesa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbxGasesMouseClicked(evt);
            }
        });

        cbxLucesa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxLucesa.setText("Luces");
        cbxLucesa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbxLucesaMouseClicked(evt);
            }
        });

        cbxFrenosa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxFrenosa.setText("Frenos");
        cbxFrenosa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbxFrenosaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbxGasesa, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxFrenosa, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxLucesa, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addComponent(cbxGasesa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(cbxFrenosa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxLucesa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        cbxGasesa.getAccessibleContext().setAccessibleName("");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Nro Turno:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Total:");

        btnRegistrarCliente.setBackground(new java.awt.Color(153, 153, 153));
        btnRegistrarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRegistrarClienteMousePressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("  REGISTRAR");

        javax.swing.GroupLayout btnRegistrarClienteLayout = new javax.swing.GroupLayout(btnRegistrarCliente);
        btnRegistrarCliente.setLayout(btnRegistrarClienteLayout);
        btnRegistrarClienteLayout.setHorizontalGroup(
            btnRegistrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnRegistrarClienteLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        btnRegistrarClienteLayout.setVerticalGroup(
            btnRegistrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnRegistrarClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Pruebas:");

        btnRegistrarCliente1.setBackground(new java.awt.Color(153, 153, 153));
        btnRegistrarCliente1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistrarCliente1MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRegistrarCliente1MousePressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("REINICIAR");

        javax.swing.GroupLayout btnRegistrarCliente1Layout = new javax.swing.GroupLayout(btnRegistrarCliente1);
        btnRegistrarCliente1.setLayout(btnRegistrarCliente1Layout);
        btnRegistrarCliente1Layout.setHorizontalGroup(
            btnRegistrarCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnRegistrarCliente1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        btnRegistrarCliente1Layout.setVerticalGroup(
            btnRegistrarCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnRegistrarCliente1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("REGISTRO DE TURNOS");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Placa Vehiculo:");

        lblCodigo.setEnabled(false);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTotala, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(comboVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(206, 206, 206))))
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(btnRegistrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistrarCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(lblTotala)
                        .addGap(1, 1, 1))
                    .addComponent(jLabel6))
                .addGap(71, 71, 71)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegistrarCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(116, 116, 116))
        );

        jPanel1.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarCliente1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarCliente1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarCliente1MousePressed

    private void cbxGasesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxGasesMouseClicked

        int mensaje = 0;
        if(cbxGasesa.isSelected() ) {
            mensaje= mensaje +10;
        }
        if (cbxFrenosa.isSelected()) {
            mensaje= mensaje + 20;
        }
        if (cbxLucesa.isSelected()){
            mensaje= mensaje + 30;
        }
        lblTotala.setText(String.valueOf(mensaje));

        // TODO add your handling code here:
    }//GEN-LAST:event_cbxGasesMouseClicked

    private void cbxFrenosaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxFrenosaMouseClicked
       
        int mensaje = 0;
        if(cbxGasesa.isSelected() ) {
            mensaje= mensaje +10;
        }
        if (cbxFrenosa.isSelected()) {
            mensaje= mensaje + 20;
        }
        if (cbxLucesa.isSelected()){
            mensaje= mensaje + 30;
        }
        lblTotala.setText(String.valueOf(mensaje));
// TODO add your handling code here:
    }//GEN-LAST:event_cbxFrenosaMouseClicked

    private void cbxLucesaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxLucesaMouseClicked
        
        int mensaje = 0;
        if(cbxGasesa.isSelected() ) {
            mensaje= mensaje +10;
        }
        if (cbxFrenosa.isSelected()) {
            mensaje= mensaje + 20;
        }
        if (cbxLucesa.isSelected()){
            mensaje= mensaje + 30;
        }
        lblTotala.setText(String.valueOf(mensaje));

        // TODO add your handling code here:
    }//GEN-LAST:event_cbxLucesaMouseClicked

    public void traerNroTurno(){
             String query = "call sp_nro_turno()";
        try {
                // String query="select usuario.usu_cedula,usu_telefono,usu_correo,usu_usuario,usuario.usu_clave from usuario where usu_usuario='"+usuario+"' and usu_clave='"+contra+"'; ";
                
                Statement st = cx.conecta().createStatement();
                ResultSet rs = st.executeQuery(query);
                
                //String u = rs.getString("tur_codigo");
                while(rs.next())
                {
                lblCodigo.setText(String.valueOf(rs.getString("tur_codigo")));
                }

                // TODO add your handling code here:
            } catch (SQLException ex) {
                Logger.getLogger(pnlRegistroTurno.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
    
    public void comboVehiculo(){
             String query = "call sp_vehiculos()";
        try {
                // String query="select usuario.usu_cedula,usu_telefono,usu_correo,usu_usuario,usuario.usu_clave from usuario where usu_usuario='"+usuario+"' and usu_clave='"+contra+"'; ";
                
                Statement st = cx.conecta().createStatement();
                ResultSet rs = st.executeQuery(query);
                
                while(rs.next())
                {
                comboVehiculo.addItem(rs.getString("veh_placa"));
                }
                
                // TODO add your handling code here:
            } catch (SQLException ex) {
                Logger.getLogger(pnlRegistroTurno.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
    
    private void btnRegistrarClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarClienteMousePressed

        try {
            // TODO add your handling code here:
            String codigo = this.lblCodigo.getText();
            String costo = this.lblTotala.getText();
            String vehiculo = this.comboVehiculo.getName();

            String query = "CALL `rtv_ist17j`.`sp_turnos`('" + codigo + "','" + costo + "','" + vehiculo + "'); ";
            Statement st = cx.conecta().createStatement();
            ResultSet rs = st.executeQuery(query);

            JOptionPane.showMessageDialog(null, "datos guardaros");

            //String query = "call sp_logeo('" + usuario + "','" + contra + "');";
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "no se guadaron los datos");
        }
    }//GEN-LAST:event_btnRegistrarClienteMousePressed

    private void btnRegistrarCliente1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarCliente1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarCliente1MouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnRegistrarCliente;
    private javax.swing.JPanel btnRegistrarCliente1;
    private javax.swing.JCheckBox cbxFrenosa;
    private javax.swing.JCheckBox cbxGasesa;
    private javax.swing.JCheckBox cbxLucesa;
    private javax.swing.JComboBox<Object> comboVehiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JTextField lblCodigo;
    private javax.swing.JTextField lblTotala;
    // End of variables declaration//GEN-END:variables
}
